import localFont from 'next/font/local'
// types
import type { Metadata } from 'next'
// components
import Header from '@/src/components/Header'
import ClientThemeProvider from '@/src/components/ClientThemeProvider'
// libs
import StyledComponentsRegistry from '@/src/lib/registry'
// styles
import '@/src/styles/globals.css'

const geistSans = localFont({
  src: '../../public/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../../public/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          <ClientThemeProvider>
            <Header />
            {children}
          </ClientThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
